
version: 2

sources:
 - name: staging
   schema: public
   database: mydb
   tables:
    - name: products
      description: "List of products for sale"
      identifier: products
    - name: orders
      description: "List of orders"
      identifier: orders

      
models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
    - name: my_second_dbt_model
      description: "restrict results"
    - name: my_python_model

    # Document within the same codebase
      description: My transformation written in Python

    # Configure in ways that feel intuitive and familiar
      config:
        materialized: table
        tags: ['python']
